spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/game
    username: root
    password: akdlapffhel
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: a
    password: a
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection-timeout: 5000
          timeout: 5000
          write timeout: 5000
    #auth-code-expiration-millis: 600000

cloud:
  aws:
    credentials:
      access-key: a
      secret-key: a
    s3:
      bucket: game-post-image
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

jwt:
  secret:
    key: and0LXNlY3JldC1rZXktZm9yLW5hdGVhbXN0b3JlLW5pY2UtdmFsdWUh

admin:
  token: a

kakao:
  rest_api_key: a
  redirect_uri: a